In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/ashrae-energy-prediction/train.csv
/kaggle/input/ashrae-energy-prediction/building_metadata.csv
/kaggle/input/ashrae-energy-prediction/sample_submission.csv
/kaggle/input/ashrae-energy-prediction/weather_test.csv
/kaggle/input/ashrae-energy-prediction/weather_train.csv
/kaggle/input/ashrae-energy-prediction/test.csv

In [2]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)
from IPython.display import HTML

In [3]:
%%time
root = '../input/ashrae-energy-prediction/'
train_df = pd.read_csv(root + 'train.csv')
weather_train_df = pd.read_csv(root + 'weather_train.csv')
test_df = pd.read_csv(root + 'test.csv')
weather_test_df = pd.read_csv(root + 'weather_test.csv')
building_meta_df = pd.read_csv(root + 'building_metadata.csv')
sample_submission = pd.read_csv(root + 'sample_submission.csv')

CPU times: user 30.9 s, sys: 4.56 s, total: 35.5 s
Wall time: 35.7 s

In [4]:
#checking shapes
print('Size of train_df data', train_df.shape)
print('Size of test_df data', test_df.shape)
print('Size of weather_train_df data', weather_train_df.shape)
print('Size of weather_test_df data', weather_test_df.shape)
print('Size of building_meta_df data', building_meta_df.shape)

Size of train_df data (20216100, 4)
Size of test_df data (41697600, 4)
Size of weather_train_df data (139773, 9)
Size of weather_test_df data (277243, 9)
Size of building_meta_df data (1449, 6)

In [5]:
## Function to reduce the DF size
def reduce_mem_usage(df, verbose=True):
    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
    start_mem = df.memory_usage().sum() / 1024**2    
    for col in df.columns:
        col_type = df[col].dtypes
        if col_type in numerics:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)    
    end_mem = df.memory_usage().sum() / 1024**2
    if verbose: print('Mem. usage decreased to {:5.2f} Mb ({:.1f}% reduction)'.format(end_mem, 100 * (start_mem - end_mem) / start_mem))
    return df

In [6]:
#reducing memory
train_df = reduce_mem_usage(train_df)
test_df = reduce_mem_usage(test_df)
weather_train_df = reduce_mem_usage(weather_train_df)
weather_test_df = reduce_mem_usage(weather_test_df)
building_meta_df = reduce_mem_usage(building_meta_df)

Mem. usage decreased to 289.19 Mb (53.1% reduction)
Mem. usage decreased to 596.49 Mb (53.1% reduction)
Mem. usage decreased to  3.07 Mb (68.1% reduction)
Mem. usage decreased to  6.08 Mb (68.1% reduction)
Mem. usage decreased to  0.03 Mb (60.3% reduction)

In [7]:
train_df.head()

   building_id  meter            timestamp  meter_reading
0            0      0  2016-01-01 00:00:00            0.0
1            1      0  2016-01-01 00:00:00            0.0
2            2      0  2016-01-01 00:00:00            0.0
3            3      0  2016-01-01 00:00:00            0.0
4            4      0  2016-01-01 00:00:00            0.0

In [8]:
#converting timestamp to date time
train_df['timestamp'] = pd.to_datetime(train_df['timestamp'], format='%Y-%m-%d %H:%M:%S')
test_df['timestamp'] = pd.to_datetime(test_df['timestamp'], format='%Y-%m-%d %H:%M:%S')

In [9]:
weather_train_df.head()

,site_id,timestamp,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,0,2016-01-01 00:00:00,25.000000,6.0,20.00000,NaN,1019.5,0.0,0.000000
1,0,2016-01-01 01:00:00,24.406250,NaN,21.09375,-1.0,1020.0,70.0,1.500000
2,0,2016-01-01 02:00:00,22.796875,2.0,21.09375,0.0,1020.0,0.0,0.000000
3,0,2016-01-01 03:00:00,21.093750,2.0,20.59375,0.0,1020.0,0.0,0.000000
4,0,2016-01-01 04:00:00,20.000000,2.0,20.00000,-1.0,1020.0,250.0,2.599609

In [10]:
#converting to pd.datetime
weather_train_df['timestamp'] = pd.to_datetime(weather_train_df['timestamp'])
weather_test_df['timestamp'] = pd.to_datetime(weather_test_df['timestamp'])

In [11]:
building_meta_df.head()

   site_id  building_id primary_use  square_feet  year_built  floor_count
0        0            0   Education         7432      2008.0          NaN
1        0            1   Education         2720      2004.0          NaN
2        0            2   Education         5376      1991.0          NaN
3        0            3   Education        23685      2002.0          NaN
4        0            4   Education       116607      1975.0          NaN

In [12]:
#merging building data to train and test data
train_df = train_df.merge(building_meta_df, on='building_id', how='left')
test_df = test_df.merge(building_meta_df, on='building_id', how='left')

In [13]:
del building_meta_df

In [14]:
train_df.head()

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,floor_count
0,0,0,2016-01-01,0.0,0,Education,7432,2008.0,NaN
1,1,0,2016-01-01,0.0,0,Education,2720,2004.0,NaN
2,2,0,2016-01-01,0.0,0,Education,5376,1991.0,NaN
3,3,0,2016-01-01,0.0,0,Education,23685,2002.0,NaN
4,4,0,2016-01-01,0.0,0,Education,116607,1975.0,NaN

In [15]:
weather_train_df.head()

,site_id,timestamp,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,0,2016-01-01 00:00:00,25.000000,6.0,20.00000,NaN,1019.5,0.0,0.000000
1,0,2016-01-01 01:00:00,24.406250,NaN,21.09375,-1.0,1020.0,70.0,1.500000
2,0,2016-01-01 02:00:00,22.796875,2.0,21.09375,0.0,1020.0,0.0,0.000000
3,0,2016-01-01 03:00:00,21.093750,2.0,20.59375,0.0,1020.0,0.0,0.000000
4,0,2016-01-01 04:00:00,20.000000,2.0,20.00000,-1.0,1020.0,250.0,2.599609

In [16]:
#merging weather data to train and test data
train_df = train_df.merge(weather_train_df, on=['site_id','timestamp'], how='left')
test_df = test_df.merge(weather_test_df, on=['site_id','timestamp'], how='left')

In [17]:
del weather_train_df, weather_test_df

In [18]:
#checking the shapes again
print(train_df.shape)
print(test_df.shape)

(20216100, 16)
(41697600, 16)

In [19]:
train_df.head()

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,floor_count,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,0,0,2016-01-01,0.0,0,Education,7432,2008.0,NaN,25.0,6.0,20.0,NaN,1019.5,0.0,0.0
1,1,0,2016-01-01,0.0,0,Education,2720,2004.0,NaN,25.0,6.0,20.0,NaN,1019.5,0.0,0.0
2,2,0,2016-01-01,0.0,0,Education,5376,1991.0,NaN,25.0,6.0,20.0,NaN,1019.5,0.0,0.0
3,3,0,2016-01-01,0.0,0,Education,23685,2002.0,NaN,25.0,6.0,20.0,NaN,1019.5,0.0,0.0
4,4,0,2016-01-01,0.0,0,Education,116607,1975.0,NaN,25.0,6.0,20.0,NaN,1019.5,0.0,0.0

In [20]:
#dropping row id
test_df.drop('row_id',axis=1,inplace=True)

In [21]:
#creating a function for count of missing values and % of missing values for d1 dataframe
def missing_data(d1):
    missing_data1 = pd.DataFrame(round(d1.isnull().sum().sort_values(ascending=False)/len(d1.index)*100,2), columns=['% of missing value'])
    missing_data1['Count of Missing Values'] = d1.isnull().sum()
    return missing_data1

In [22]:
#checking missing data in training file
missing_data(train_df)

                    % of missing value  Count of Missing Values
floor_count                      82.65                 16709167
year_built                       59.99                 12127645
cloud_coverage                   43.66                  8825365
precip_depth_1_hr                18.54                  3749023
wind_direction                    7.17                  1449048
sea_level_pressure                6.09                  1231669
wind_speed                        0.71                   143676
dew_temperature                   0.50                   100140
air_temperature                   0.48                    96658
square_feet                       0.00                        0
primary_use                       0.00                        0
site_id                           0.00                        0
meter_reading                     0.00                        0
timestamp                         0.00                        0
meter                             0.00                        0
building_id                       0.00                        0

In [23]:
#checking missing values in test date as the value is very high
missing_data(test_df)

                    % of missing value  Count of Missing Values
floor_count                      82.61                 34444320
year_built                       58.99                 24598080
cloud_coverage                   46.87                 19542180
precip_depth_1_hr                18.71                  7801563
wind_direction                    7.14                  2978663
sea_level_pressure                6.04                  2516826
wind_speed                        0.72                   302089
dew_temperature                   0.63                   260799
air_temperature                   0.53                   221901
square_feet                       0.00                        0
primary_use                       0.00                        0
site_id                           0.00                        0
timestamp                         0.00                        0
meter                             0.00                        0
building_id                       0.00                        0

In [25]:
#dropping the floor count column from both the test and train data
train_df.drop('floor_count', axis=1, inplace=True)
test_df.drop('floor_count', axis=1, inplace=True)

In [45]:
#creating new column of age of the building and replacing null values with -1 and deleting yearbuilt column from both the datasets
train_df['Age'] = train_df['timestamp'].dt.year - train_df['year_built']
test_df['Age'] = test_df['timestamp'].dt.year - test_df['year_built']

In [51]:
#replacing null in age with -1
train_df['Age'] = train_df['Age'].replace(np.nan, -1)
test_df['Age'] = test_df['Age'].replace(np.nan, -1)

In [52]:
#deleting year_build column from both the datasets
train_df.drop('year_built', axis=1, inplace=True)
test_df.drop('year_built', axis=1, inplace=True)

In [54]:
#checking the missing data again
print('Missing data in train data')
print(missing_data(train_df))
print('Missing data in test data')
print(missing_data(test_df))

Missing data in train data
                    % of missing value  Count of Missing Values
cloud_coverage                   43.66                  8825365
precip_depth_1_hr                18.54                  3749023
wind_direction                    7.17                  1449048
sea_level_pressure                6.09                  1231669
wind_speed                        0.71                   143676
dew_temperature                   0.50                   100140
air_temperature                   0.48                    96658
Age                               0.00                        0
square_feet                       0.00                        0
primary_use                       0.00                        0
site_id                           0.00                        0
meter_reading                     0.00                        0
timestamp                         0.00                        0
meter                             0.00                        0
building_id                       0.00                        0
Missing data in test data
                    % of missing value  Count of Missing Values
cloud_coverage                   46.87                 19542180
precip_depth_1_hr                18.71                  7801563
wind_direction                    7.14                  2978663
sea_level_pressure                6.04                  2516826
wind_speed                        0.72                   302089
dew_temperature                   0.63                   260799
air_temperature                   0.53                   221901
Age                               0.00                        0
square_feet                       0.00                        0
primary_use                       0.00                        0
site_id                           0.00                        0
timestamp                         0.00                        0
meter                             0.00                        0
building_id                       0.00                        0

In [ ]:
sns.scatterplot(train_df.cloud_coverage,train_df.wind_speed)