#### Principal Component Analysis

The properties of PCA as mentioned in the video are as follows:
1. They're weighted linear combinations of the original variables.
2. They're perpendicular to each other. 
3. They capture maximum variance of the data and are ordered.

Let's go ahead and verify these properties

In [1]:
import pandas as pd 
import numpy as np

In [5]:
#Let's now take the following dataframe
a = [[0,0,0],[1,2,3],[2,4,5],[3,6,2],[4,8,3],[5,10,1]]
b = ['X','Y','Z']
dat = pd.DataFrame(a,columns = b)
dat

   X   Y  Z
0  0   0  0
1  1   2  3
2  2   4  5
3  3   6  2
4  4   8  3
5  5  10  1

In [7]:
from sklearn.decomposition import PCA
pca=PCA(svd_solver ="randomized",random_state =42)

In [4]:
#Importing the PCA module
from sklearn.decomposition import PCA
pca = PCA(svd_solver='randomized', random_state=42)

In [8]:
#Applying PCA on the dataset
pca.fit(dat)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=42,
  svd_solver='randomized', tol=0.0, whiten=False)

In [71]:
#Let's check the components
pca.components_.round(3)

array([[-0.447, -0.894, -0.031],
       [-0.014, -0.028,  1.   ],
       [ 0.894, -0.447,  0.   ]])

In [85]:
np.linalg.inv(pca.components_) @ dat.T

array([[ 0.        ,  2.20860827,  3.52278935,  0.36483448,  0.78458837,
        -1.47893931],
       [ 0.        , -2.29098739, -4.13476118, -3.74246699, -5.13902719,
        -5.1939466 ],
       [ 0.        ,  1.96810221,  3.93620441,  5.90430662,  7.87240882,
         9.84051103]])

### Property 1: Principal Components are weighted linear combinations of Original Variables

In [86]:
#The original variables are the original axes here given by X(1,0,0), Y(0,1,0) and Z(0,0,1)
#We need to show that PCs that are formed are the linear combinations of X,Y and Z.
lincom  = pca.components_[0]
setvec = np.array([[1,0,0],[0,1,0],[0,0,1]])
x,y,z = np.linalg.solve(setvec, lincom)
round(x,2),round(y,2),round(z,2)

(-0.45, -0.89, -0.03)

Hence it is verfied that these PCs are linear combinations of the original variables

In [93]:
round(5.66 + dat.X * x + dat.Y * y+ dat.Z * z,2)

0    5.66
1    3.33
2    1.04
3   -1.11
4   -3.37
5   -5.55
dtype: float64

### Property 2: Principal Components are perpendicular to each other

In [21]:
#For verifying this we would be calculating the dot product of any of the two PCs.
#We know that dot product of any 2 perpendicular vectors is 0.
round(np.dot(pca.components_[1],pca.components_[0]))

0.0

### Property 3: Principal Components capture maximum variance and are ordered.

In [37]:
#First let us see what is the variance given by the PCs
pca.explained_variance_ratio_.round(0)

array([1., 0., 0.])

In [33]:
pca.explained_variance_ratio_.round(2)

array([0.85, 0.15, 0.  ])

In [27]:
np.var(dat)

X     2.916667
Y    11.666667
Z     2.555556
dtype: float64

#### Let's verify this calculation by projecting the data onto the principal components

In [30]:
#We can directly use the pca function pca.fit_transform
#This is equivalent to the basis transformation that we did earlier.
#To project the data
dat_new2 = pca.fit_transform(dat)
cols = ['X','Y','Z']
dat_new3 = pd.DataFrame(dat_new2, columns = cols).round(2)
dat_new3

      X     Y    Z
0  5.66 -2.16  0.0
1  3.33  0.77 -0.0
2  1.03  2.70  0.0
3 -1.11 -0.37  0.0
4 -3.37  0.56  0.0
5 -5.55 -1.51  0.0

In [90]:
dat_new3.X

0    5.66
1    3.33
2    1.03
3   -1.11
4   -3.37
5   -5.55
Name: X, dtype: float64

In [31]:
np.var(dat_new3)

X    14.596147
Y     2.546514
Z     0.000000
dtype: float64

Hence it has been verified.

In [32]:
#let's do one final calculation
sum(np.var(dat))

17.138888888888886

In [33]:
sum(np.var(dat_new3))

17.14266111111111

#### This is what PCA does. It doesn't change the total variance of the dataset. It only rearranges them in the direction of maximum variances

In [101]:
import numpy as np 
from sklearn.decomposition import pca

In [97]:
data =pd.read_csv("MyFoodRatings.csv")

In [98]:
data.head()

,Name,Chicken,Mutton,Paneer,ChowMein,SpringRolls,Momo,Sushi,Ramen,Tempura
0,A,5,5,5,0,0,0,0,0,0
1,B,4,4,4,0,0,0,0,0,0
2,C,3,3,3,0,0,0,0,0,0
3,D,2,2,2,0,0,0,0,0,0
4,E,0,0,0,2,2,2,0,0,0

In [128]:
U,s,VT = np.linalg.svd(data.iloc[:,1:], full_matrices=True)

In [129]:
display(data.shape,U.shape,s.shape,VT.shape)

(12, 10)

(12, 12)

(9,)

(9, 9)

In [136]:
np.diag(s[:3].round(2))

array([[12.73,  0.  ,  0.  ],
       [ 0.  , 10.58,  0.  ],
       [ 0.  ,  0.  ,  8.85]])

In [140]:
pd.DataFrame(VT).head(3)

,0,1,2,3,4,5,6,7,8
0,-0.57735,-0.57735,-0.57735,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.00000,0.00000,0.00000,-0.637875,-0.512261,-0.575068,0.000000,0.000000,0.000000
2,0.00000,0.00000,0.00000,0.000000,0.000000,0.000000,-0.476163,-0.557638,-0.679933

In [148]:
data =pd.read_csv("FoodRatings_all_same_5_4_3.csv")
data =data.drop("Name",axis=1)
U, s, VT = np.linalg.svd(data, full_matrices=True)

In [149]:
s.round(2)

array([17.32, 13.86, 10.39,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ])

In [153]:
pd.DataFrame(U).corr().round()

     0    1    2    3    4    5    6    7    8    9    10   11
0   1.0 -0.0 -0.0 -0.0  0.0 -0.0  0.0  0.0  0.0  0.0 -0.0  0.0
1  -0.0  1.0 -0.0  0.0  0.0 -0.0  0.0  0.0  0.0 -0.0 -0.0  0.0
2  -0.0 -0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  -0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4   0.0  0.0  0.0  0.0  1.0 -0.0  0.0  0.0  0.0 -0.0 -0.0 -0.0
5  -0.0 -0.0  0.0  0.0 -0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
9   0.0 -0.0  0.0  0.0 -0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
10 -0.0 -0.0  0.0  0.0 -0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
11  0.0  0.0  0.0  0.0 -0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0